Vagrant.configure("2") do |config|
  config.vm.box = "developerinlondon/ubuntu_lxc_xenial_x64"
  config.vm.box_check_update = false
  config.vm.provider :lxc do |lxc|
    # Same effect as 'customize ["modifyvm", :id, "--memory", "1024"]' for VirtualBox
    lxc.customize 'cgroup.memory.limit_in_bytes', '1024M'
    lxc.customize 'network.ipv4', '10.0.3.15/24'
  end
end