---
# defaults file for ansible-openldap
openldap_admin_password: 'P@55w0rd'
openldap_admin_user: 'admin'
openldap_org: 'example'
openldap_tld: 'org'
openldap_base: 'dc={{ openldap_org }},dc={{ openldap_tld }}'
openldap_bind_id: 'cn={{ openldap_bind_user }},{{ openldap_base }}'
openldap_bind_user: '{{ openldap_admin_user }}'
openldap_debian_packages:
  - slapd
  - ldap-utils
  - phpldapadmin
openldap_organizationalunits:  #defines OU's to populate
  - users
  - groups
openldap_phpldapadmin_hide_warnings: 'true'
openldap_populate: true  #defines if openldap DB should be populated with openldap_organizationalunits, openldap_posixgroups and openldap_users
openldap_posixgroups:  #defines groups to create within OU's
  - name: admins
    ou: groups
    gidNum: 5000  #start group numbers at 5000 and up
  - name: developers
    ou: groups
    gidNum: 5001
openldap_server_host: '127.0.0.1'  #defines host for phpLDAPadmin
openldap_users:
  - FirstName: Chris
    LastName: Balz
    ou: users  #defines OU name
    uidNum: 10000  #start user numbers at 10000 and up
    gidNum: 5000  #defines gidNum from openldap_posixgroups
    password: 'P@55w0rd'
    loginShell: /bin/bash
    homeDirectory: /home/cbalz
  - FirstName: Chris
    LastName: Balz
    ou: users  #defines OU name
    uidNum: 10001  #start user numbers at 10000 and up
    gidNum: 5000  #defines gidNum from openldap_posixgroups
    password: 'P@55w0rd'
    loginShell: /bin/bash
    homeDirectory: /home/cbalz
pri_domain_name: '{{ openldap_org }}.{{ openldap_tld }}'
