jenkins_directory: /data/jenkins

directories:
  - '{{ jenkins_directory }}/plugins'
  - '{{ jenkins_directory }}/slaves/cd'
  - /data/.ivy2

configs:
  - config.xml

#plugins:
#  - github.hpi
#  - git.hpi
#  - credentials.jpi
#  - scm-api.hpi
#  - matrix-project.jpi
#  - git-client.hpi
#  - github-api.hpi

jobs:
  - books-service
#
#my_jenkins_plugins:
#  token-macro:
#    enabled: yes
#  build-pipeline-plugin:
#    version: "1.4.9"
#    pinned: no
#    enabled: yes

#my_jenkins_plugins:
#  token-macro:
#    enabled: yes
#  build-pipeline-plugin:
#    version: "1.4.9"
##    pinned: no
#    enabled: yes


# Optional method of pinning a specific version of Jenkins and/or overriding the
# default Jenkins packaging URL.
# jenkins_version: "1.644"
# jenkins_pkg_url: "https://www.example.com"

# Change this to `latest` to update Jenkins if a newer version is available.
jenkins_package_state: present

jenkins_connection_delay: 5
jenkins_connection_retries: 60
jenkins_home: /var/lib/jenkins
jenkins_hostname: localhost
jenkins_http_port: 8080
jenkins_jar_location: /opt/jenkins-cli.jar
jenkins_url_prefix: ""
jenkins_java_options: "-Djenkins.install.runSetupWizard=false"

jenkins_plugins:
  jquery:
    version: "1.11.2-0"
  build-pipeline-plugin:
    version: "1.5.7.1"
    pinned: no
    enabled: yes


jenkins_plugins_state: present
jenkins_plugin_updates_expiration: 86400
jenkins_plugin_timeout: 30

jenkins_admin_username: admin
jenkins_admin_password:
jenkins_admin_password_file: ""
jenkins_admin_token: "a4e0876fd6f745f482b123055ac0d801"
jenkins_admin_token_file: "/var/lib/jenkins/secrets/initialAdminPassword"

jenkins_process_user: jenkins
jenkins_process_group: "{{ jenkins_process_user }}"

jenkins_init_changes:
  - option: "JENKINS_ARGS"
    value: "--prefix={{ jenkins_url_prefix }}"
  - option: "{{ jenkins_java_options_env_var }}"
    value: "{{ jenkins_java_options }}"
