jenkins_directory: /data/jenkins

directories:
  - '{{ jenkins_directory }}/plugins'
  - '{{ jenkins_directory }}/slaves/cd'
  - /data/.ivy2

configs:
  - config.xml

#plugins:
#  - github.hpi
#  - git.hpi
#  - credentials.jpi
#  - scm-api.hpi
#  - matrix-project.jpi
#  - git-client.hpi
#  - github-api.hpi

jobs:
  - books-service
#
#my_jenkins_plugins:
#  token-macro:
#    enabled: yes
#  build-pipeline-plugin:
#    version: "1.4.9"
#    pinned: no
#    enabled: yes

#my_jenkins_plugins:
#  token-macro:
#    enabled: yes
#  build-pipeline-plugin:
#    version: "1.4.9"
##    pinned: no
#    enabled: yes


# Optional method of pinning a specific version of Jenkins and/or overriding the
# default Jenkins packaging URL.
jenkins_version: "2.82"
# jenkins_pkg_url: "https://www.example.com"

# Change this to `latest` to update Jenkins if a newer version is available.
jenkins_package_state: present

jenkins_connection_delay: 5
jenkins_connection_retries: 60
jenkins_home: /var/lib/jenkins
jenkins_hostname: localhost
jenkins_http_port: 8080
jenkins_jar_location: /opt/jenkins-cli.jar
jenkins_url_prefix: ""
jenkins_java_options: "-Djenkins.install.runSetupWizard=false"

jenkins_plugins:
  jquery:
    version: "1.11.2-0"
  build-pipeline-plugin:
    version: "1.5.7.1"
    pinned: no
    enabled: yes
  github:
    version: "1.28.0"
#    enabled: yes

jenkins_plugins_state: present
jenkins_plugin_updates_expiration: 86400
jenkins_plugin_timeout: 30

jenkins_admin_username: admin
jenkins_admin_password: admin
jenkins_admin_password_file: ""
jenkins_admin_token: ""
jenkins_admin_token_file: ""

jenkins_process_user: jenkins
jenkins_process_group: "{{ jenkins_process_user }}"

jenkins_init_changes:
  - option: "JENKINS_ARGS"
    value: "--prefix={{ jenkins_url_prefix }}"
  - option: "{{ jenkins_java_options_env_var }}"
    value: "{{ jenkins_java_options }}"

#jenkins_admin_token: "{{ lookup('file', '/var/lib/jenkins/secrets/initialAdminPassword') }}"

jenkins_ssh_key_file: "/home/ev/.ssh/id_rsa_jenkins_github"

jenkins_ssh_fingerprints:                   # Set known hosts for ssh
  - "bitbucket.org,131.103.20.167 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw=="
  - "github.com,204.232.175.90 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
