---
- name: Ensure that the ngircd package is installed
  tags: ngircd
  become: true
  yum:
    enablerepo: epel
    name: ngircd
    state: present
  register: ngircd_yum

- name: Attempting to overlay ngircd configuration
  tags: ngircd
  become: true
  template:
    src: ngircd.conf.j2
    dest: /etc/ngircd.conf
    owner: root
    group: ngircd
    mode: 0660
  notify: restart ngircd
  register: ngircd_template
  when:
    - ngircd_yum|success

- name: Creating message of the day, if applicable.
  tags: ngircd
  become: true
  template:
    src: ngircd.motd.j2
    dest: /etc/ngircd.motd
    owner: root
    group: ngircd
    mode: 0660
  notify: restart ngircd
  when:
    - ngircd_global_motdfile is defined
    - ngircd_yum|success

- name: Ensure that ngircd is started and enabled on boot
  tags: ngircd
  become: true
  service:
    enabled: yes
    name: ngircd
    state: started
  when:
    - ngircd_template|success
    - ngircd_yum|success
...
