---
- name: Ensure that the ngircd package is installed
  tags: ngircd
  become: true
  apt:
    name: ngircd
    state: present
  register: ngircd_yum

- name: Attempting to overlay ngircd configuration
  tags: ngircd
  become: true
  template:
    src: ngircd.conf.j2
    dest: /etc/ngircd/ngircd.conf
    owner: irc
    group: irc
    mode: 0660
  notify: restart ngircd
  register: ngircd_template
  when:
    - ngircd_yum|success

- name: Creating message of the day, if applicable.
  tags: ngircd
  become: true
  template:
    src: ngircd.motd.j2
    dest: /etc/ngircd/ngircd.motd
    owner: irc
    group: irc
    mode: 0777
  notify: restart ngircd
  when:
    - ngircd_global_motdfile is defined
    - ngircd_yum|success

- file:
    path: /home/christopherbalz/service/ssl_files_2016
    state: directory
    mode: 0777

- file:
    path: /home/christopherbalz/service/bip/log
    state: directory
    mode: 0777

- name: Files are present
  copy:
    src: "{{ item }}"
    dest: /home/christopherbalz/service/ssl_files_2016/{{ item }}
    mode: 0600
    owner: irc
    group: irc
  with_items:
    - ngircd_dhparam.pem
    - treelogic-swe.com.crt
    - treelogic-swe.com.key

- name: Files are present
  copy:
    src: bip.pem
    dest: /home/christopherbalz/service/ssl_files_2016/bip.pem
    mode: 0600
#    become: false
    owner: "{{ ansible_ssh_user }}"
#    group: vagrant

- name: Files are present
  copy:
    src: Commands.txt
    dest: /usr/share/doc/ngircd/Commands.txt
    mode: 0777

- name: Files are present
  copy:
    src: ngircd.motd
    dest: /etc/ngircd/ngircd.motd
    mode: 0777

- file:
    path: /var/run/ngircd
    state: directory
    mode: 0777


- name: Ensure that ngircd is started and enabled on boot
  tags: ngircd
  become: true
  service:
    enabled: yes
    name: ngircd
    state: started
  when:
    - ngircd_template|success
    - ngircd_yum|success

- name: Ensure that the bip package is installed
  tags: ngircd
  become: true
  apt:
    name: bip
    state: present

#- name: Ensure that the git package is installed
#  tags: ngircd
#  become: true
#  apt:
#    name: git
#    state: present

#- name: Install bip dependencies.
#  apt: name={{ item }} state=present
#  with_items:
#    - make
#    - gcc

#
#- git:
#    repo: 'https://github.com/zwily/bip.git'
#    dest: /srv/checkout
#    version: master
#
#- name: Build bip.
#  command: ./configure --enable-oidentd && make
#  args:
#    chdir: /srv/checkout

- file:
    path: ~/service/bip
    state: directory
    mode: 0755

- name: Attempting to overlay bip configuration
  tags: ngircd
  become: false
  template:
    src: bip.conf.j2
    dest: /home/christopherbalz/service/bip/bip.conf
#    owner: vagrant
#    group: irc
    mode: 0660
#  notify: restart ngircd
#  register: ngircd_template
#  when:
#    - ngircd_yum|success

- name: Stop bip.
  become: true
  command: bash -c "cat /var/run/bip.pid | xargs kill -9 || true"

- name: Remove bip pid file.
  file:
    path: /home/christopherbalz/service/bip/bip.pid
    state: absent

- name: Run bip.
  command: bip -f /home/christopherbalz/service/bip/bip.conf
  become: false

...
